### ISSUE TITLE
ltx-2 error

### ISSUE THREAD

**Issue by jost848** [Lightricks/ComfyUI-LTXVideo#346]
CLIPTextEncode
CUDA error: invalid argument
Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by pschivo** [comment]
Same error here.

**Comment by nickxar1** [comment]
same here :O

**Comment by NullCode1337** [comment]
Duplicate of #318 (already has solution inside it)

**Comment by nickxar1** [comment]
thanks, can confirm "--disable-pinned-memory" in .bat file works 👍

**Comment by pschivo** [comment]
Another solution that worked for me was using LowVRAM nodes that come with LTX Custom Nodes (i have a RTX 5070ti) and the 4-bit TE.

<img width="728" height="649" alt="Image" src="https://github.com/user-attachments/assets/1a562e45-994f-40e7-bf86-8fbe5ae4f185" />
